### ISSUE TITLE
Hubot Slack cannot connect due to "Cannot set property 'room' of undefined"

### ISSUE THREAD

**Issue by Roach** [slackapi/hubot-slack#404]
#### Description
> Hubot Slack cannot connect due to "Cannot set property 'room' of undefined"

#### Reproducible in:
hubot-slack version: 4.3.3
OS version(s):
Device(s):

#### Steps to reproduce:

1. connect hubot to Enterprise team

✅ I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
✅ I've read and agree to the [Code of Conduct](https://github.com/slackapi/hubot-slack/blob/master/CODE_OF_CONDUCT.md).
✅ I've searched for any related issues and avoided creating a duplicate issue.

**Comment by Roach** [comment]
logs from dev4slack discussion:

```
[Mon Mar 27 2017 10:58:46 GMT-0700 (PDT)] INFO Slack client now connected
[Mon Mar 27 2017 10:58:46 GMT-0700 (PDT)] ERROR TypeError: Cannot set property 'room' of undefined
  at SlackBot.reaction (/home/mikedc/gobot-wdp/gobot/node_modules/hubot-slack/src/bot.coffee:194:5, <js>:248:17)
  at RTMClient.<anonymous> (/home/mikedc/gobot-wdp/gobot/node_modules/hubot-slack/src/bot.coffee:1:1, <js>:3:61)
  at RTMClient.emit (/home/mikedc/gobot-wdp/gobot/node_modules/eventemitter3/index.js:116:35)
  at RTMClient.emit (/home/mikedc/gobot-wdp/gobot/node_modules/@slack/client/lib/clients/client.js:83:39)
  at RTMClient._handleWsMessageViaEventHandler (/home/mikedc/gobot-wdp/gobot/node_modules/@slack/client/lib/clients/rtm/client.js:466:10)
  at RTMClient.handleWsMessage (/home/mikedc/gobot-wdp/gobot/node_modules/@slack/client/lib/clients/rtm/client.js:420:10)
  at WebSocket.wrapper (/home/mikedc/gobot-wdp/gobot/node_modules/@slack/client/node_modules/lodash/lodash.js:4994:19)
  at emitTwo (events.js:106:13)
  at WebSocket.emit (events.js:191:7)
  at Receiver.ontext (/home/mikedc/gobot-wdp/gobot/node_modules/ws/lib/WebSocket.js:841:10)
  at /home/mikedc/gobot-wdp/gobot/node_modules/ws/lib/Receiver.js:536:18
  at Receiver.applyExtensions (/home/mikedc/gobot-wdp/gobot/node_modules/ws/lib/Receiver.js:371:5)
  at /home/mikedc/gobot-wdp/gobot/node_modules/ws/lib/Receiver.js:508:14
  at Receiver.flush (/home/mikedc/gobot-wdp/gobot/node_modules/ws/lib/Receiver.js:347:3)
  at Receiver.finish (/home/mikedc/gobot-wdp/gobot/node_modules/ws/lib/Receiver.js:541:12)
  at Receiver.expectHandler (/home/mikedc/gobot-wdp/gobot/node_modules/ws/lib/Receiver.js:499:31)
  at Receiver.add (/home/mikedc/gobot-wdp/gobot/node_modules/ws/lib/Receiver.js:103:24)
  at TLSSocket.realHandler (/home/mikedc/gobot-wdp/gobot/node_modules/ws/lib/WebSocket.js:825:20)
  at emitOne (events.js:96:13)
  at TLSSocket.emit (events.js:188:7)
  at readableAddChunk (_stream_readable.js:176:18)
  at TLSSocket.Readable.push (_stream_readable.js:134:10)
  at TLSWrap.onread (net.js:548:20)
```
and

```
info: Rate limited, will retry 45 seconds
```

The team above has ~10 members, but this is also effecting Enterprise large teams.

**Comment by aoberoi** [comment]
* seems to only happen in Enterprise teams, and the team does not have any shared channels

**Comment by aoberoi** [comment]
*Summary*

Actions on files in public channels trigger events on the entire team (or workspace) whether your bot is in that channel or not. notice this isn’t unique to enterprise. also notice that its all actions (reaction, comments, etc). on a non-enterprise team, this usually isn’t an issue, since you have a complete set of users inside the `dataStore` for that single team. the reason this is a problem on enterprise is because some of those actions may come from someone outside your own workspace. when this happens, its impossible to look up that user in the `dataStore`.

*So what do we do?*

In hubot, my recommendation is that we find every instance where we query a user out of the `dataStore` and create a branch of code for what happens if this lookup fails. It’s not great, but the most common approach will probably just be to swallow the event and not let anything bubble up to the application.

Thinking more holistically, we need to create a solution for this at the `dataStore` level to try and hide this issue from users of the node-slack-sdk. Off the top of my head, i honestly think we need a major version bump and to deprecate the `dataStore` API in favor of something that is async so that we could fallback to querying the `users.info` web api method.
