### ISSUE TITLE
Cannot read property 'brain' of undefined

### ISSUE THREAD

**Issue by zl4bv** [slackapi/hubot-slack#496]
### Description

I've tried updating from `hubot-slack` version 4.4.0 to 4.5.0 and now I'm seeing the error described in the issue title. It seems to happen after being connected to Slack RTM for several seconds. Once the error has occurred hubot re-connects to Slack RTM and the error occurs again and again.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

Possibly related to #477?

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version: 4.5.0

node version: v10.0.0

OS version(s): macOS 10.13.3

#### Steps to reproduce:

1. execute hubot `bin/hubot --adapter slack`
2. wait for hubot to connect to Slack RTM
3. error occurs

#### Expected result:

* hubot-slack stores data in brain without error
* hubot remains connected to Slack RTM

#### Actual result:

* An error is logged by hubot
* hubot reconnects to Slack RTM

#### Attachments:

```
[Thu Jun 14 2018 14:49:17 GMT+1200 (NZST)] INFO Connected to Slack RTM
[Thu Jun 14 2018 14:49:17 GMT+1200 (NZST)] DEBUG Received reaction message from: Uredacted, reaction: omg, item type: file
[Thu Jun 14 2018 14:49:17 GMT+1200 (NZST)] DEBUG No listeners executed; falling back to catch-all
[Thu Jun 14 2018 14:49:41 GMT+1200 (NZST)] ERROR TypeError: Cannot read property 'brain' of undefined
    at RTMClient.SlackClient.updateUserInBrain (/Users/ben.vidulich/repos/myrobot/app/node_modules/hubot-slack/src/client.coffee:283:26)
    at RTMClient.emit (/Users/ben.vidulich/repos/myrobot/app/node_modules/eventemitter3/index.js:116:35)
    at RTMClient._handleWsMessageViaEventHandler (/Users/ben.vidulich/repos/myrobot/app/node_modules/@slack/client/lib/clients/rtm/client.js:482:10)
    at RTMClient.handleWsMessage (/Users/ben.vidulich/repos/myrobot/app/node_modules/@slack/client/lib/clients/rtm/client.js:436:10)
    at WebSocket.wrapper (/Users/ben.vidulich/repos/myrobot/app/node_modules/@slack/client/node_modules/lodash/lodash.js:4949:19)
    at WebSocket.emit (events.js:182:13)
    at Receiver.ontext (/Users/ben.vidulich/repos/myrobot/app/node_modules/ws/lib/WebSocket.js:841:10)
    at /Users/ben.vidulich/repos/myrobot/app/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/Users/ben.vidulich/repos/myrobot/app/node_modules/ws/lib/Receiver.js:371:5)
    at /Users/ben.vidulich/repos/myrobot/app/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/Users/ben.vidulich/repos/myrobot/app/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.finish (/Users/ben.vidulich/repos/myrobot/app/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/Users/ben.vidulich/repos/myrobot/app/node_modules/ws/lib/Receiver.js:499:31)
    at Receiver.add (/Users/ben.vidulich/repos/myrobot/app/node_modules/ws/lib/Receiver.js:103:24)
    at TLSSocket.realHandler (/Users/ben.vidulich/repos/myrobot/app/node_modules/ws/lib/WebSocket.js:825:20)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:280:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onread (net.js:638:20)
```

This is the contents of my `package.json`:

```json
{
  "name": "myrobot",
  "version": "0.0.0",
  "private": true,
  "author": "Ben Vidulich <email removed>",
  "description": "A glorious robot",
  "dependencies": {
    "coffee-script": "^1.12.7",
    "hubot": "^2.19.0",
    "hubot-diagnostics": "0.0.2",
    "hubot-help": "^0.2.0",
    "hubot-redis-brain": "^0.0.4",
    "hubot-scripts": "^2.17.2",
    "hubot-slack": "^4.5.0",
    "needle": "^2.0.1",
    "url-parse": "1.4.0"
  },
  "engines": {
    "node": "0.10.x"
  }
}
```

**Comment by sinisterstuf** [comment]
Can confirm. It seems to be coming from this line: https://github.com/slackapi/hubot-slack/commit/3f2280b8891ed422fd036094eded326b396606f6#diff-351dc31e106a2dbec7562a4de2562812R283 introduced when `updateUserInBrain` was moved from bot.coffee to client.coffee.

**Comment by shanedewael** [comment]
@zl4bv @sinisterstuf Sorry about that, there was a bug on the release that affected `user_change` events. I was able to reproduce and fix the bug. Could you update to `v4.5.1`?

**Comment by zl4bv** [comment]
I've updated to v4.5.1 and it's working as expected. Thanks so much, @shanedewael!

**Comment by sinisterstuf** [comment]
Indeed, it's fixed, thanks!
