### ISSUE TITLE
Unhandled rejection Error: not_in_channel 

### ISSUE THREAD

**Issue by tommywo** [slackapi/hubot-slack#516]
### Description

Hubot fails sending message to public slack channel if it isn't already in it.

> Unhandled rejection Error: not_in_channel
  at handleHttpResponse (/opt/hubot/node_modules/@slack/client/lib/clients/transports/call-transport.js:103:17)
  at handleTransportResponse (/opt/hubot/node_modules/@slack/client/lib/clients/transports/call-transport.js:153:19)
  at apply (/opt/hubot/node_modules/@slack/client/node_modules/lodash/lodash.js:478:17)
  at wrapper (/opt/hubot/node_modules/@slack/client/node_modules/lodash/lodash.js:5337:16)
  at Request.handleRequestTranportRes (/opt/hubot/node_modules/@slack/client/lib/clients/transports/request.js:21:5)
  at apply (/opt/hubot/node_modules/@slack/client/node_modules/lodash/lodash.js:478:17)
  at Request.wrapper [as _callback] (/opt/hubot/node_modules/@slack/client/node_modules/lodash/lodash.js:5337:16)
  at Request.self.callback (/opt/hubot/node_modules/@slack/client/node_modules/request/request.js:186:22)
  at emitTwo (events.js:126:13)
  at Request.emit (events.js:214:7)
  at Request.<anonymous> (/opt/hubot/node_modules/@slack/client/node_modules/request/request.js:1060:10)
  at emitOne (events.js:116:13)
  at Request.emit (events.js:211:7)
  at IncomingMessage.<anonymous> (/opt/hubot/node_modules/@slack/client/node_modules/request/request.js:980:12)
  at Object.onceWrapper (events.js:313:30)
  at emitNone (events.js:111:20)
  at IncomingMessage.emit (events.js:208:7)
  at endReadableNT (_stream_readable.js:1056:12)
  at _combinedTickCallback (internal/process/next_tick.js:138:11)
  at process._tickCallback (internal/process/next_tick.js:180:9)

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Reproducible in:

hubot-slack version: 4.4.0

**Comment by michael-bowen-sp** [comment]
@aoberoi So what is the proposed method for dealing with async errors? I'm having trouble err handling robot.messageRoom because it is async.

**Comment by michael-bowen-sp** [comment]
I guess I will just use ES6 instead of CoffeeScript that seems to work.
