### ISSUE TITLE
How to send blocks from hubot to slack?

### ISSUE THREAD

**Issue by gregoryguillou** [slackapi/hubot-slack#559]
### Description

When I add `blocks` in `robot.adapter.client.web.chat.postMessage` as described in [the slack-api documentation](https://api.slack.com/methods/chat.postMessage), I get `Unhandled rejection Error: invalid_array_arg`. Is is supported to send `blocks` from Hubot to Slack? How can I do that?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version: 4.6.0

node version: 11.13

OS version(s): Any

#### Steps to reproduce:

1. I've added the following very script to my hubot script

```javascript
  robot.hear(/(.*) (attach)$/i, response => {
    robot.adapter.client.web.chat.postMessage(
      response.message.room,
      "Hi",
      {
        as_user: true,
        unfurl_links: false,
        blocks: [{"type": "section", "text": {"type": "plain_text", "text": "Hello world"}}]
      }
    );
  });
```

2. I ask `attach` to hubot

3. It fails with:

```text
error: Response not OK:  invalid_array_arg
Unhandled rejection Error: invalid_array_arg
  at handleHttpResponse (/app/node_modules/@slack/client/lib/clients/transports/call-transport.js:103:17)
  at handleTransportResponse (/app/node_modules/@slack/client/lib/clients/transports/call-transport.js:153:19)
  at apply (/app/node_modules/lodash/lodash.js:478:17)
  at wrapper (/app/node_modules/lodash/lodash.js:5323:16)
  at Request.handleRequestTranportRes (/app/node_modules/@slack/client/lib/clients/transports/request.js:21:5)
  at apply (/app/node_modules/lodash/lodash.js:478:17)
  at Request.wrapper [as _callback] (/app/node_modules/lodash/lodash.js:5323:16)
  at Request.self.callback (/app/node_modules/request/request.js:185:22)
  at Request.emit (events.js:193:13)
  at Request.<anonymous> (/app/node_modules/request/request.js:1161:10)
  at Request.emit (events.js:193:13)
  at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)
  at Object.onceWrapper (events.js:281:20)
  at IncomingMessage.emit (events.js:198:15)
  at endReadableNT (_stream_readable.js:1142:12)
  at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

#### Expected result:

Sorry to bother you. This is a general direction question. I wonder if it is actually supported or if I'm doing something wrong. The dependency with @slack/client is actually 3.16.1-sec.2 so I wonder if that is why.

**Comment by Kullersj** [comment]
Blocks are not supported in version of @slack/client that hubot uses. You need to set up an API call and call it using HTTP instead of using the SDK

**Comment by gregoryguillou** [comment]
Thank you @Kullersj
