### ISSUE TITLE
Executing robot.adapter.client.web.chat.postEphemeral always return invalid_array_arg

### ISSUE THREAD

**Issue by lukaszlenart** [slackapi/hubot-slack#599]
### Description

I try to use `chat.postEphemeral` but each time I get `error: Response not OK:  invalid_array_arg`

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version: 4.8.0

node version: 6.11.1

OS version(s): Linux

#### Steps to reproduce:

I created the following code

```coffee
  robot.hear /.*thanks.*/i, (res) ->
    message =
      channel: res.message.rawMessage.channel
      text: "some message"
      user: res.message.user.id
      as_user: "true"

    robot.logger.info "Sends response to #{res.message.rawMessage.channel} as #{JSON.stringify(message)}"
    robot.adapter.client.web.chat.postEphemeral(message)
      .then (result) ->
        robot.logger.info result
      .catch (error) ->
        robot.logger.error error
```

and each time I get

```
error: Response not OK:  invalid_array_arg
```

I tested the same with [chat.postEphemeral](https://api.slack.com/methods/chat.postEphemeral/test) and it just works

#### Expected result:

See an ephemeral message in the channel 

#### Actual result:

An error message

```
[Tue Jun 16 2020 20:57:57 GMT+0200 (CEST)] ERROR Error: invalid_array_arg
  at handleHttpResponse (/hubot/node_modules/hubot-slack/node_modules/@slack/client/lib/clients/transports/call-transport.js:103:17)
  at handleTransportResponse (/hubot/node_modules/hubot-slack/node_modules/@slack/client/lib/clients/transports/call-transport.js:153:19)
  at apply (/hubot/node_modules/lodash/lodash.js:478:17)
  at wrapper (/hubot/node_modules/lodash/lodash.js:5317:16)
  at Request.handleRequestTranportRes (/hubot/node_modules/hubot-slack/node_modules/@slack/client/lib/clients/transports/request.js:21:5)
  at apply (/hubot/node_modules/lodash/lodash.js:478:17)
  at Request.wrapper [as _callback] (/hubot/node_modules/lodash/lodash.js:5317:16)
  at Request.self.callback (/hubot/node_modules/request/request.js:185:22)
  at emitTwo (events.js:126:13)
  at Request.emit (events.js:214:7)
  at Request.<anonymous> (/hubot/node_modules/request/request.js:1154:10)
  at emitOne (events.js:116:13)
  at Request.emit (events.js:211:7)
  at IncomingMessage.<anonymous> (/hubot/node_modules/request/request.js:1076:12)
  at Object.onceWrapper (events.js:313:30)
  at emitNone (events.js:111:20)
  at IncomingMessage.emit (events.js:208:7)
  at endReadableNT (_stream_readable.js:1064:12)
  at _combinedTickCallback (internal/process/next_tick.js:139:11)
  at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by seratch** [comment]
@lukaszlenart Thanks for taking the time to report this.

I know this is confusing and frustrating but `hubot-slack` project still depends on very old node-slack-sdk (v3). So, the method's interface is a bit different from the latest one. Here is [the `chat.postEphemeral` method definition in v3](https://github.com/slackapi/node-slack-sdk/blob/v3.16.1-sec.2/lib/clients/web/facets/chat.js#L83-L91). 

So, modifying your code as below should work (I've verified it works).

```coffeescript
    # robot.adapter.client.web.chat.postEphemeral(message)
    robot.adapter.client.web.chat.postEphemeral(
      res.message.rawMessage.channel,
      "some message",
      res.message.user.id
    )
```

**Comment by lukaszlenart** [comment]
Thanks, that works! Is there a way to pass `as_user`?

**Comment by lukaszlenart** [comment]
nvm, found it :)

**Comment by seratch** [comment]
I'm glad it worked out! Allow me to close this issue not but if you have anything further, please feel free to reopen it or write in.
