### ISSUE TITLE
ERROR SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Sandaru48** [slackapi/hubot-slack#616]
**Describe the bug**
I'm trying to get Grafana dashboard to slack API using hubot. Once tyoe @jarvis-bot graf list, its  giving following error 
```
ubuntu@ubuntu:~/hubot$ HUBOT_SLACK_TOKEN=xoxb-XXXXXXXXXXXXXXXXXXXX ./bin/hubot  --adapter slack
audited 168 packages in 4.264s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

[Sun Jan 03 2021 08:15:18 GMT+0000 (Coordinated Universal Time)] INFO hubot-slack adapter v4.8.1
warn: SlackDataStore is deprecated and will be removed in the next major version. See project documentation for a migration guide.
warn: SlackDataStore is deprecated and will be removed in the next major version. See project documentation for a migration guide.
[Sun Jan 03 2021 08:15:19 GMT+0000 (Coordinated Universal Time)] INFO Logged in as @jarvis-bot in workspace Team-PSMT
[Sun Jan 03 2021 08:15:20 GMT+0000 (Coordinated Universal Time)] INFO Connected to Slack RTM
[Sun Jan 03 2021 08:15:20 GMT+0000 (Coordinated Universal Time)] INFO hubot-redis-brain: Using default redis on localhost:6379
[Sun Jan 03 2021 08:15:21 GMT+0000 (Coordinated Universal Time)] INFO hubot-redis-brain: Data for hubot brain retrieved from Redis
[Sun Jan 03 2021 08:16:06 GMT+0000 (Coordinated Universal Time)] ERROR SyntaxError: Unexpected token < in JSON at position 0
  at JSON.parse (<anonymous>:null:null)
  at /home/ubuntu/hubot/node_modules/hubot-grafana/src/grafana.coffee:428:7, <js>:424:21
  at IncomingMessage.<anonymous> (/home/ubuntu/hubot/node_modules/scoped-http-client/src/index.js:95:22)
  at IncomingMessage.emit (events.js:327:22)
  at endReadableNT (internal/streams/readable.js:1327:12)
  at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**To Reproduce**

1. Installed proetheus, node_exporter as service and installed grafana with image render plugin using docker-compose in a Raspberry pi 4 (armv8)
2. See error

**Expected behavior**
getting grafana dashboard without error

**Screenshots**
![image](https://user-images.githubusercontent.com/39979402/103474883-1ff9d300-4dce-11eb-83a2-acff8e9dfe5b.png)
![image](https://user-images.githubusercontent.com/39979402/103474903-47e93680-4dce-11eb-80ce-184e8b9207ea.png)

**Software:**
 - Grafana: v7.3.6
 - Hubot: 3.3.2
 - Adapter: Slack
 - Node: v14.15.3
 - NPM: 6.14.9

**Comment by seratch** [comment]
Hello, thanks for asking the question. According to the stacktrace you've shared, the error seems to be raised by `hubot-grafana`, not `hubot-slack`.

```
[Sun Jan 03 2021 08:16:06 GMT+0000 (Coordinated Universal Time)] ERROR SyntaxError: Unexpected token < in JSON at position 0
  at JSON.parse (<anonymous>:null:null)
  at /home/ubuntu/hubot/node_modules/hubot-grafana/src/grafana.coffee:428:7, <js>:424:21
  at IncomingMessage.<anonymous> (/home/ubuntu/hubot/node_modules/scoped-http-client/src/index.js:95:22)
  at IncomingMessage.emit (events.js:327:22)
  at endReadableNT (internal/streams/readable.js:1327:12)
  at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by Sandaru48** [comment]
Hi @seratch Thank you.
